# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: Swift XCTest on PR

on:
  pull_request:
    branches:
      - develop
      - main

jobs:
  test:
    runs-on: macos-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Xcode
      - name: Set up Xcode environment
        run: |
          sudo xcode-select -s /Applications/Xcode.app

      # Run tests
      - name: Run iOS Unit Tests
        run: |
          xcodebuild test \
            -scheme NetNetNet \
            -destination 'platform=iOS Simulator,name=iPhone 13,OS=15.0' \
            -sdk iphonesimulator

